# 따릉이 대여소 정보
* https://www.bikeseoul.com/
* 따릉이 홈페이지에 나와있는 대여소 정보를 가져온다.

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import requests
import pandas as pd

In [3]:
url = 'https://www.bikeseoul.com/commonCode/getStationName.do'
 
%time response = requests.post(url=url)
response

CPU times: user 52.5 ms, sys: 23.6 ms, total: 76.1 ms
Wall time: 13.1 s

In [4]:
data = response.json()

In [5]:
df = pd.DataFrame(data['stationList'])
df.shape

(1462, 20)

In [6]:
df.head()

,addVal1,addVal2,addVal3,cdDesc1,cdDesc2,comCd,comCdName,comCdNameEn,comCdNameJa,comCdNameKo,comCdNameZh,comUpCd,crudFlg,lang,mileageUseYn,rentFee,stationId,stationName,stationNo,viewFlg
0,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,None,108. 서교동 사거리,None,None
1,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,None,503. 더샵스타시티 C동 앞,None,None
2,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,None,729. 서부식자재마트 건너편,None,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,None,731. 서울시 도로환경관리센터,None,None
4,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,None,732. 신월동 이마트,None,None

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 20 columns):
addVal1         0 non-null object
addVal2         0 non-null object
addVal3         0 non-null object
cdDesc1         0 non-null object
cdDesc2         0 non-null object
comCd           0 non-null object
comCdName       0 non-null object
comCdNameEn     0 non-null object
comCdNameJa     0 non-null object
comCdNameKo     0 non-null object
comCdNameZh     0 non-null object
comUpCd         0 non-null object
crudFlg         0 non-null object
lang            1462 non-null object
mileageUseYn    0 non-null object
rentFee         0 non-null object
stationId       0 non-null object
stationName     1462 non-null object
stationNo       0 non-null object
viewFlg         0 non-null object
dtypes: object(20)
memory usage: 228.5+ KB

In [8]:
df.isnull().sum()

addVal1         1462
addVal2         1462
addVal3         1462
cdDesc1         1462
cdDesc2         1462
comCd           1462
comCdName       1462
comCdNameEn     1462
comCdNameJa     1462
comCdNameKo     1462
comCdNameZh     1462
comUpCd         1462
crudFlg         1462
lang               0
mileageUseYn    1462
rentFee         1462
stationId       1462
stationName        0
stationNo       1462
viewFlg         1462
dtype: int64

In [9]:
stations = df[['lang', 'stationId', 'stationName']]
stations.head()

      lang stationId        stationName
0  LAG_001      None       108. 서교동 사거리
1  LAG_001      None   503. 더샵스타시티 C동 앞
2  LAG_001      None   729. 서부식자재마트 건너편
3  LAG_001      None  731. 서울시 도로환경관리센터
4  LAG_001      None       732. 신월동 이마트

In [10]:
stations['id'] = df['stationName'].apply(lambda x : x.split('.')[0] if '.' in x else x )
stations['name'] = df['stationName'].apply(lambda x : x.split('.')[1] if '.' in x else x )
stations.head()

      lang stationId        stationName   id           name
0  LAG_001      None       108. 서교동 사거리  108        서교동 사거리
1  LAG_001      None   503. 더샵스타시티 C동 앞  503    더샵스타시티 C동 앞
2  LAG_001      None   729. 서부식자재마트 건너편  729    서부식자재마트 건너편
3  LAG_001      None  731. 서울시 도로환경관리센터  731   서울시 도로환경관리센터
4  LAG_001      None       732. 신월동 이마트  732        신월동 이마트

In [11]:
get_station_url = 'https://www.bikeseoul.com/commonCode/getStation.do'
 
%time response = requests.post(url=get_station_url)
response

CPU times: user 21.3 ms, sys: 4.18 ms, total: 25.5 ms
Wall time: 137 ms

In [12]:
data = response.json()
stations = pd.DataFrame(data['stationList'])
stations

,addVal1,addVal2,addVal3,cdDesc1,cdDesc2,comCd,comCdName,comCdNameEn,comCdNameJa,comCdNameKo,comCdNameZh,comUpCd,crudFlg,lang,mileageUseYn,rentFee,stationId,stationName,stationNo,viewFlg
0,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,23,송파구,None,None
1,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,24,성북구,None,None
2,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,25,중랑구,None,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,26,노원구,None,None
4,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,27,도봉구,None,None
5,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,28,금천구,None,None
6,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,29,구로구,None,None
7,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,30,동작구,None,None
8,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,31,관악구,None,None
9,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,32,서초구,None,None
10,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,33,강남구,None,None
11,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,34,강북구,None,None
12,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,22,강서구,None,None
13,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,10,종로구,None,None
14,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,11,중구,None,None
15,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,12,마포구,None,None
16,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,13,서대문구,None,None
17,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,14,성동구,None,None
18,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,15,광진구,None,None
19,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,16,동대문구,None,None
20,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,18,양천구,None,None
21,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,19,용산구,None,None
22,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,17,영등포구,None,None
23,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,20,은평구,None,None
24,None,None,None,None,None,None,None,None,None,None,None,None,None,LAG_001,None,None,21,강동구,None,None